### PR TITLE
Add asyncOptions setting to enable passport asynchronous options feat…

### PR DESCRIPTION
**Pull request by bnielsen1965**
…ure. Updated config get call to support 'authentication' and 'auth' settings. Eliminated need for babel transpiling and adjusted code pattern to more closely match authentication-local.

The main changes here are the new asyncOptions setting when configuring the module and the call to get the authentication configuration will check both 'authentication' and 'auth'.

The asyncOptions setting is used like the following...
```javascript
// use the user credentials from the authentication request to bind to the ldap server.
app.configure(ldap({
  asyncOptions: req => ({ server: { bindDn: req.body.username, bindCredentials: req.body.password } })
}));
```

The change to read multiple auth types was simple this...
```javascript
let authOptions = app.get('authentication') || app.get('auth') || {};
```

And I hope I'm not stepping on any toes but I also removed the requirement to transpile the src files. It seems that the only benefit of applying babel was to be able to use the import statement in place of require and it added a lot of overhead and made the code a bit different to follow when compared to the other authentication modules.

I ran the npm test script and everything checks out.

### CODE REVIEW

**Comment by bnielsen1965** [comment]
Actually it appears that the transpiler did provide an additional benefit, the resulting code was compatible with node v4.

It looks like authentication-local does not support node v4, is this a travis test that should be removed from the module?

**Comment by daffl** [comment]
Yes, the new plugin structure is not compatible with Node 4. The version can be removed from the Travis configuration at https://github.com/feathersjs-ecosystem/feathers-authentication-ldap/blob/master/.travis.yml#L5

**Comment by bnielsen1965** [comment]
Tests pass now.

But I think this may be a mistake...
https://github.com/feathersjs-ecosystem/feathers-authentication-ldap/pull/24/files#diff-6d186b954a58d5bb740f73d84fe39073R36

```javascript
throw new Error(`Can not find app.passport. Did you initialize feathers-authentication before @feathersjs/authentication-ldap?`);
```

Is the @feathersjs wrong here, since this is coming from the ecosystem?

**Comment by KB1RMA** [comment]
This is a great feature add! I'm in need of this exact thing. Do you have any plans to merge this patch?

**Comment by robbiedhickey** [comment]
I also have a use case for this - being able to authenticate with different domain controllers depending on the request. This would be a very elegant solution to the problem!

**Comment by KB1RMA** [comment]
@daffl Is there any work you see remaining on this patch before merging? I was planning on forking this and maintaining myself for a project if it isn't going to be merged. Obviously trying to avoid that and more than happy to help with any clean up on this patch if it's still needed.

**Comment by daffl** [comment]
Released as v0.3.0. Sorry it took so long but the truth is that this repository needs a maintainer who is actually using it to review and test things.

I am more than happy to transfer ownership to whoever is more qualified to do this, there should never really be a need of having to maintain your own forks. The time commitment is fairly minimal and all I'd ask would be to find a new maintainer if it you no longer want to do it.

**Pull request merged**
